# Generated by Django 5.0.1 on 2024-02-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dons_des_sangs', '0005_donateur_date_don'),
    ]

    operations = [
        migrations.AddField(
            model_name='donateur',
            name='date_don_active',
            field=models.DateField(blank=True, null=True),
        ),
    ]
