# Generated by Django 5.0.1 on 2024-02-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dons_des_sangs', '0006_donateur_date_don_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donateur',
            name='pre_don',
        ),
        migrations.AddField(
            model_name='donateur',
            name='a_fait_don',
            field=models.BooleanField(default=False),
        ),
    ]
