# Generated by Django 5.0.1 on 2024-03-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dons_des_sangs', '0007_remove_donateur_pre_don_donateur_a_fait_don'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donateur',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='donateur',
            name='otp_created_at',
        ),
        migrations.RemoveField(
            model_name='donateur',
            name='otp_is_used',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
